### ISSUE TITLE
Do not wait for transitionEnd if transitionStart is not fired

### ISSUE THREAD

**Issue by CSchulz** [robinparisi/tingle#101]
In most cases tests are run without any css which does not work with the current implementation.
If the browser supports CSS animations, it is waiting for the `transitionEnd` event regardless if transitions are started or not.

/cc @ajafff

**Comment by robinparisi** [comment]
https://github.com/robinparisi/tingle/pull/115#issuecomment-476333377

**Comment by robinparisi** [comment]
So, I've choose to remove the use of transition event. It should be better for your case since there is no easy way to handle transitions.
