### ISSUE TITLE
Recommended way to set width?

### ISSUE THREAD

**Issue by joshk6** [robinparisi/tingle#104]
Without attempting to set size, the modal is kind of too large for my purposes.  (I'm using the Tingle to display alert boxes like "Please limit your selection to 3 items max" sort of thing.

It would be good if the documentation suggested the best way to set the width (and height) without breaking your css.

(Thanks for this btw, just what I needed to as not to break some of the other frameworks which implement tediously complicated mechanisms to display a simple modal with an "OK" button.)

**Comment by SID-London** [comment]
Seconded. I've been trying to figure out how to do this for a while now without breaking other bits of the site.

**Comment by drakakisgeo** [comment]
I changed the width by css, seems ok to me.

`.tingle-modal-box{
    max-width:700px;
}`

**Comment by robinparisi** [comment]
Indeed, tingle provides a minimalist CSS, feel free to use the best method that fits your needs!

For example, you can add a custom class:

```js
var modal = new tingle.modal({
    cssClass: ['tingle--modal']
});
```

and add a custom CSS to match .tingle--modal with the desire width.
