### ISSUE TITLE
Missing semicolon

### ISSUE THREAD

**Issue by miskith** [robinparisi/tingle#106]
At the very end of the script is missing semicolon breaking other scripts that may follow. This is just issue of built tingle.js , minified version is ok.

**Comment by robinparisi** [comment]
You're right, my bad! I'm using a new conf with ESLint with no semicolon but didn't pay attention to the *Auto Semicolon Insertion* rule.

**Comment by robinparisi** [comment]
Hey @miskith, a quick question about this one. 

I assume you're concatenating the script. Which tool do you use?

**Comment by miskith** [comment]
Don't see this info related in any way, but ok. Slowly switching from gulp to webpack, but the part using tingle is so far still using gulp (specifically gulp-concat).

**Comment by robinparisi** [comment]
Gulp is perfectly fine (I use Gulp too) but in this case, gulp-concat should handle the semicolon insertion as gulp-uglify does with the minified version.
