### ISSUE TITLE
Dynamic content

### ISSUE THREAD

**Issue by orangethakkali** [robinparisi/tingle#108]
Hi,
I am passing data from PHP to setContent() method for dynamically displaying images. However, when I pass PHP variable, instead of image, the actual <IMG> code is displayed.

```
var e = '{{$images}}'; // $images will be like <IMG SRC=image1.jpg>
modal.setContent(e);
```

**Comment by emmanuelballery** [comment]
Hi,

Is this ``{{$images}}`` from Twig or some kind of PHP template engine ? Automatic escaping is enabled by default in a lot of them. For example in Twig you'd have to use the ``raw`` filter to mark the variable as safe. 

Something like ``var e = '{{$images|raw}}';`` (for Twig see https://twig.symfony.com/doc/2.x/filters/raw.html or find your template engine documentation regarding escaping strategy).

**Comment by robinparisi** [comment]
@emmanuelballery response should do the trick 😃
