### ISSUE TITLE
Allow multiple modals

### ISSUE THREAD

**Issue by emmanuelballery** [robinparisi/tingle#109]
Salut les Troyens,

I'm digging up an old issue (#41) but I'd like to use multiple modals (a modal within another modal ...) whilst keeping the previous ones in the background. I'm currectly moving the node in the DOM each time I'm creating a modal :

```js
const modal = new tingle.modal(modalOptions);
document.body.append(modal.modal);
```

Correct me if I'm wrong but there is only one change to consider in https://github.com/robinparisi/tingle/blob/master/dist/tingle.js#L55 :

```js
// instead of inserting before the first body node
document.body.insertBefore(this.modal, document.body.firstChild)

// just append them to the body
document.body.append(this.modal)
```

Is there something I'm missing that forces us to put the new node right after the document body and prevents this functionality from being implemented ?

**Comment by robinparisi** [comment]
Hey @emmanuelballery,

Good question, I will try to do some tests but I think there are potential issues with events and body actions (class and scroll).

**Comment by JuicyLung91** [comment]
This feature would be great. 
So there would be the possibility to open a different modal after one is closed. Dialog like.

**Comment by DennysDionigi** [comment]
Still wishes here.
Looking for a positive confirmation button, which may allow opening a new modal, just after closing the old one.
