### ISSUE TITLE
possible to remove gif from bower? 

### ISSUE THREAD

**Issue by kunkinkan** [robinparisi/tingle#11]
The tingle.gif example file is taking up more than 3MB. I'm using tingle in an app, with automated distribution, would be best if this file was not in there, but not sure how to go about that. Easiest would be to have it removed from the project ;-) If you would consider it , thanks!

**Comment by robinparisi** [comment]
Hi,

Which method are you using to integrate tingle in your project (bower, npm, simple download...) ?

**Comment by wesleywesley** [comment]
Bower.

**Comment by wesleywesley** [comment]
I suppose I could remove it via a script before deployment though, so if you would like to keep it in, no problem.

**Comment by robinparisi** [comment]
Nop, you're totally right. This file should be ignored by bower during install. I will update the bower.json as soon as possible.
