### ISSUE TITLE
Not working with VueJS / NuxtJS

### ISSUE THREAD

**Issue by Loschcode** [robinparisi/tingle#112]
Great modal system. I'm trying to integrate it within my VueJS / NuxtJS project, so I installed through npm and tried to simply include it.

```import tingle from 'tingle.js'```

But it crashes completely

```ReferenceError
document is not defined

internal/modules/cjs/loader.js:721:30
Module._compile
internal/modules/cjs/loader.js:732:10
Module._extensions..js
internal/modules/cjs/loader.js:620:32
Module.load
internal/modules/cjs/loader.js:560:12
tryModuleLoad
internal/modules/cjs/loader.js:552:3
Module._load
internal/modules/cjs/loader.js:657:17
Module.require
internal/modules/cjs/helpers.js:20:18
require
webpack:/external "tingle.js":1:
Object.tingle.js
webpack/bootstrap:25:
__webpack_require__
```

Any idea where that could be coming from ? I really want to use this modal in the project ... Thanks

**Comment by robinparisi** [comment]
Hi,

I'm not familiar with Nuxt but maybe it's related to this: https://nuxtjs.org/faq/window-document-undefine

**Comment by Loschcode** [comment]
Thanks for the quick reply, I believe you're right and it's not a tingle issue, I'll try to use this. Thanks for your input!
