### ISSUE TITLE
Can't close modal when removing transitions

### ISSUE THREAD

**Issue by RomkaLTU** [robinparisi/tingle#113]
Please remove that ugly scale effect on defaults, also when I try to remove scale ant transitions, I can't close modal when pressing outside it (overlay) even esc and close buttons doesn't work.

**Comment by RomkaLTU** [comment]
It seams that JS is waiting for transition and then attaching close events so no way to use it witout transitons, so I added more neutral tansiotion:

```
.tingle-modal-box {
  transition: opacity .3s cubic-bezier(.175, .885, .32, 1.275);
  opacity: 0;
}

.tingle-modal--visible {
  opacity: 1;
}

.tingle-modal--visible .tingle-modal-box {
  opacity: 1;
}
```

**Comment by robinparisi** [comment]
Hey @RomkaLTU,

please take a look at this: https://github.com/robinparisi/tingle/pull/115#issuecomment-476333377

**Comment by robinparisi** [comment]
So, I've choose to remove the use of transition event. It should be better for your case since there is no easy way to handle transitions.
