### ISSUE TITLE
Destroy without reference? 

### ISSUE THREAD

**Issue by kunkinkan** [robinparisi/tingle#12]
Can we have a public method that will destroy a modal if indeed there is one present? Use case if if I don't have the variable reference any more. (for example by programatically wanting to show another modal)

**Comment by robinparisi** [comment]
Hi,

I am not sure I understand the intended goal. Maybe you can share a part of your code?

**Comment by wesleywesley** [comment]
Well, I use your modal box for displaying preferences, but also when something bad happens with the app (child process quit, for example). 

So if the preferences modal is open, and that child process quits, I need to show a more important alert. So for that I need to hide that previous modal. (To which I don't have a reference in my main process (using electron).

Anyway, was able to solve it by doing this: 
```

function hidePossibleModal() {
    var nodes = document.querySelectorAll(".tingle-modal");
     Array.prototype.forEach.call(nodes, function(node) {
      node.parentNode.removeChild(node);
    });

    var body = document.querySelector('body');
    body.classList.remove("tingle-enabled");
  }

```

**Comment by robinparisi** [comment]
Indeed, if you can't keep the reference, I think the only way is to directly target the modal using his class.
