### ISSUE TITLE
Modal close button is broken in responsive mode

### ISSUE THREAD

**Issue by Phyks** [robinparisi/tingle#120]
Hi,

First, thanks for this very nice tiny library! When going to https://robinparisi.github.io/tingle/ with a device with a width of less than 540px, the modal close button (X) is a large X over the modal content.

![Screenshot_2019-05-13 Modal plugin written in pure JavaScript - Tingle](https://user-images.githubusercontent.com/3856586/57638924-18f5cf80-75af-11e9-8e5c-9ee56b4c4ad3.png)

Thanks!

**Comment by robinparisi** [comment]
Hi  @Phyks,

It should work now, sorry for the inconvenience.

**Comment by Phyks** [comment]
Thanks a lot!
