### ISSUE TITLE
Missing Semi-Colons

### ISSUE THREAD

**Issue by X25guru** [robinparisi/tingle#123]
There's a million missing semis at the end of lines; which break compressors and packers.

**Comment by shockthetoast** [comment]
While Javascript technically allows leaving off semicolons, it generally seems like a bad idea for non-minified code. It leads to a lot of ambiguity.

**Comment by X25guru** [comment]
THIS is the price to pay when you use amateur code. I've used 1000s of js "products" over the years and you're the first one to actually leave off semis on purpose. Probably why I abandoned using the code. I was just informing you that your code sucks.
