### ISSUE TITLE
When resize screen from big to small without refresh the page ,padding-bottom of modalBoxContent not recalculated again.

### ISSUE THREAD

**Issue by utohitewa** [robinparisi/tingle#125]
this.modalBoxContent.style['padding-bottom'] = this.modalBoxFooter.clientHeight + 20 + 'px'

**Comment by robinparisi** [comment]
Hi @utohitewa , 

Can you share more information about this issue (browser, steps to reproduce the bug, tingle instanciation code,...)?

**Comment by utohitewa** [comment]
when set { footer:true,stickyFooter:true }
and has long content to appear the scroll,
start page from desktop-view and resize to mobile-view,
so modalBoxFooter at mobile-view may be higher than modalBoxFooter at desktop-view
so padding-bottom of modalBoxContent should be recalculated.

**Comment by robinparisi** [comment]
Nice catch, I will try to publish a fix this week.
