### ISSUE TITLE
Enhancements: work with data

### ISSUE THREAD

**Issue by dios-oleg** [robinparisi/tingle#130]
Hello!
I like your project.

I needed functions for working with data and I added them in my fork.
The essence of functions is to transfer data to an instance of the form and receive data from the form using simple calls.

Some of them:
```
var modalWithData = new tingle.modal(/*...*/);
// ... any code

modalWithData.setEntities({
        name: 'John Doe 2', // keyName & value: name: 'name', value: 'John Doe'
        numberPhone: { // keyName: elementName Or elementId Or elementClassName
            identificationMethod: 'id', // class, id... // default name
            identificationValue: 'phone', // default keyName
            usesByForm: true, // default true
            defaultAttribute: 'value', // value, another
            multiple: false,
            value: '33',
            'data-per': 654
            //classList: [], // any parameters element
        },
        title: {
            identificationMethod: 'className', // class, id // default name
            identificationValue: 'form-title', // default keyName
            multiple: true,
            innerHTML: 'New title',
            defaultAttribute: 'innerHTML',
        },
        email: 'My email',
    })

modalWithData.getEnity('name') // returns an object 
modalWithData.setValue('title', 'Ivanov'); // sets to '.form-title' the 'Ivanov'
modalWithData.getValue('title'); // returns 'Ivanov'
modalWithData.getEntityPropertyNames('title'); // array -> ['innerHTML']
modalWithData.getSomeValues('numberPhone'); // object
modalWithData.getEnity('email', false); // object
// etc
```

I have other ideas regarding working with classes / styles (I don't want to bind to default class names).

**Comment by robinparisi** [comment]
Hi @dios-oleg,

Thanks for your interest but I prefer to keep the lib as simple as possible and from my point of view, modal shouldn't handle data.

However, I agree with the class system that needs to be reviewed.

**Comment by dios-oleg** [comment]
It is possible that not everyone needs to use data pass to and from a form, as well as alerts, multiple modals, and even moving open modals. They also increase the size of the library, expand the API and use cases.

Can them be used as extensions?

When using the modal window as a choice or data entry, nevertheless, data handling and data exchange with the server occurs.
