### ISSUE TITLE
Is closing and reopening the modal supposed to keep the old one in dom?

### ISSUE THREAD

**Issue by droidzone** [robinparisi/tingle#131]
I have several elements in a modal which is created on the fly. When I close and reopen the modal, I find that these elements are still in DOM, leading to weird effects of duplication when I try to use data attached to these elements.

Should I do:
`onClose: function () {				
				modal.destroy()
			},`
to prevent this behaviour?

**Comment by emmanuelballery** [comment]
You can use ``this.destroy();``.

**Comment by aardvark82** [comment]
Same issue - calling this.destroy();. onClose() still keeps the modal in DOM - any tips on how to track this down?

**Comment by aardvark82** [comment]
Actually the problem was that I was binding multiple listeners on the same object - I eventually had to call 
        $(".contact").unbind();

on the initiating elem that spawns the modal so that it only gets called once and spawns 1 model
