### ISSUE TITLE
Sticky Footer Windows 10 / Chrome 78

### ISSUE THREAD

**Issue by nbcnc** [robinparisi/tingle#133]
Been using Tingle for years... love the plugin.  Using version 15.1.  I noticed a bug on **Windows 10 / Chrome 78** only and I was able to fix it with CSS.  Just adding it here in case anyone else has a similar problem.

Notice how the sticky footer (where the arrow is pointed) doesn't stick to the bottom of a scrolling modal. 

<img width="528" alt="Screen Shot 2019-10-31 at 8 57 09 AM" src="https://user-images.githubusercontent.com/27741514/67949471-284cf180-fbbe-11e9-87d4-c12a2ddf8092.png">

I fixed it by adding `position: sticky` to the CSS file

<img width="437" alt="Screen Shot 2019-10-31 at 8 58 27 AM" src="https://user-images.githubusercontent.com/27741514/67949572-4e729180-fbbe-11e9-9d7d-dc548a418eab.png">

Not sure why.  Adding `position: sticky` doesn't seem to have any adverse side-effects in other browsers.  Tested in latest versions of IE, Firefox, and Chrome.

**Comment by robinparisi** [comment]
Hi @nbcnc,

I'm note sure if it's a Chrome 78 bug or a bad implementation with tingle but I would rather avoid to use `position: sticky` according to the current support: https://caniuse.com/#feat=css-sticky

**Comment by robinparisi** [comment]
After some tests, the bug seems to be related to backdrop-filter property. I can't go deeper right now since I'm on vacation but you can override CSS as a quick fix:

```css
.tingle-modal {
    backdrop-filter: none;
}
```

**Comment by nbcnc** [comment]
Thanks @robinparisi, I'll try that -- but the support for `backdrop-filter` looks about the same or less than `position:sticky` according to: https://caniuse.com/#feat=css-backdrop-filter.  CanIUse says IE 11 has no support for `position:sticky` it but it seemed to work fine for me in Edge.  Hard to tell what to do with this apparent bug but I appreciate the suggestion!

**Comment by robinparisi** [comment]
Indeed, but I consider `backdrop-filter` as an optional enhancement (you can still achieve the same blur effect without it). 

Modal position is trickier: I don't know why `position: sticky` allows to fix the Chrome 78 bug but it doesn't seem logical to me. I will try to understand this behavior and push a fix after my vacations.

**Comment by robinparisi** [comment]
After doing some research, it seems that Chrome has the correct implementation for `position: fixed` (https://developer.mozilla.org/en-US/docs/Web/CSS/position):

> The element is removed from the normal document flow, and no space is created for the element in the page layout. It is positioned relative to the initial containing block established by the viewport, except when one of its ancestors has a transform, perspective, or filter property set to something other than none (see the CSS Transforms Spec), in which case that ancestor behaves as the containing block. (Note that there are browser inconsistencies with perspective and filter contributing to containing block formation.) Its final position is determined by the values of top, right, bottom, and left.

It explains why the div with `backdrop-filter` now act as a containing block.

**Comment by robinparisi** [comment]
I just published a patch using a pseudo-element to avoid modifying the parent container.
