### ISSUE TITLE
The nth-child does not work with Tingle.js

### ISSUE THREAD

**Issue by gusbemacbe** [robinparisi/tingle#136]
Salut @robinparisi !

```
.tingle-modal__close:nth-child(1) 
{
  background-color: var(--laranja-600) !important;
}

.tingle-modal__close:nth-child(2) 
{
  background-color: var(--roxo-600) !important;
}
```

**Comment by blex41** [comment]
`:nth-child`, as its name kind of suggests, is the Nth child of its parent. When you open the modal, the close button is always the first child of the modal. Using something like `.tingle-modal:nth-child(1) .tingle-modal__close` would be more fitting, if the modals are always in the right order ([does not seem to be the case, they're reversed](https://jsfiddle.net/d60f4jz8/))

**Comment by robinparisi** [comment]
thanks @blex41 for the response!
