### ISSUE TITLE
Allow script tags inside modal content

### ISSUE THREAD

**Issue by nickeatingsalsage** [robinparisi/tingle#137]
Allow script tags to execute on since many sites todays still use server-side rendering. Thank you.

**Comment by robinparisi** [comment]
Hi,

I'm not sure to understand the main purpose. If you want to execute code on opening, use callback. If you want to pass a script with your content (as a string) then Tingle should use eval wich is a really bad idea (perfs, security, debuging,...)

In any case, this is not related to server side rendering.
