### ISSUE TITLE
Modal Scrollbar Disappears in Chrome 85.0.4183.83

### ISSUE THREAD

**Issue by eihabi** [robinparisi/tingle#141]
Hi @robinparisi,

The latest version of Chrome has a bug that hides the scroll bars on Windows 10 as seen on [this screenshot](https://imgur.com/a/2QQxTUT).

It appears that this issue was also present in Chrome 41.

There are a couple of workarounds that I was able to find, but nothing that is acceptable:

1) [Disable hardware acceleration](https://stackoverflow.com/questions/12560797/google-chrome-vertical-scrollbar-disappears-on-some-web-pages-maybe-due-to-a-s#answer-48381513). This resolves the problem but hardly a fix for users/visitors.
2) Apply `transform:translateZ(0);` [to the modal](https://github.com/twbs/bootstrap/issues/16297#issuecomment-93437408). This shows the scroll bar but breaks the DOM flow and causes footer content that are attached to the bottom of the screen to lose their position.

Apart from a re-write to contain the scrollbar within the modal content div I'm not really sure what can be done here.

Thoughts?

**Comment by robinparisi** [comment]
Hi @eihabi,

Thanks for filling out an issue. I can't test on Windows for now but I will try to do so as soon as possible.
