### ISSUE TITLE
Replacement for resize

### ISSUE THREAD

**Issue by QuestionDevelopment** [robinparisi/tingle#144]
Hello Robin!
Thanks a lot for this project.  It is exactly what I was looking for.

I noticed on your website it says resize is depreciated.  I don't see any replacement for it.  Do you have a recommended way to handle size controls?

**Comment by emmanuelballery** [comment]
Use `checkOverflow()`.

**Comment by QuestionDevelopment** [comment]
Ah ok, it seems like all sizing is handled via css.  If I am mistaken can you please reply back.  Otherwise thank you for explaining.

**Comment by emmanuelballery** [comment]
Sizing of the modal box is done via CSS. But if you load async contents in it (for example images or ajax results) the content may be overflowing without any way to scroll it through. Calling `checkOverflow()` when content is loaded fixes this issue by displaying the scrollbar (adding a class to the body). I think that is all.
