### ISSUE TITLE
v0.2 doesn't return object

### ISSUE THREAD

**Issue by QuestionDevelopment** [robinparisi/tingle#145]
Hello again,
Sorry for the multiple issues.  I just updated to v0.2 and as far as I can tell, 

`new tingle.modal`

no longer returns an object.  I didn't dig too deep because this might all be by design but I noticed that the Modal function doesn't call init any longer.  

Like I said, maybe this is your solution to allowing multiple modals to run at same time however none of your document is valid if this is the case (and I have no idea how to use your script any more).

Switchting back to v0.15.2 resolved the error message I was having

`Uncaught TypeError: object.addFooterBtn is not a function`

**Comment by emmanuelballery** [comment]
`v0.2` is older (Apr 5, 2016) than `v0.15.2` (Nov 9, 2019) or `v0.15.3` (Apr 30).

See https://github.com/robinparisi/tingle/releases (`v0.2` is indeed marked as the last Github release but I don't think it is intended).

**Comment by QuestionDevelopment** [comment]
Yeah you got it exactly.

Thanks for your time.  I think the issue with the "latest" is because you need a tag on the commit with the v#.
