### ISSUE TITLE
How to set static modal in html?

### ISSUE THREAD

**Issue by aalfiann** [robinparisi/tingle#147]
Because I'm using react, so I need to render the UI first in html.

With using this library, how to just open the modal and without setContent?

**Comment by robinparisi** [comment]
Hi,

You can write a custom wrapper for react (I'm not familiar with this framework) or pass content in a more classical way, there is a lot of possibilities, but for now, there is now easy way since a React plugin would be required.

**Comment by aalfiann** [comment]
Hey, after write this issue, suddenly I found the trick.

After react succesfull in render, then I just call the modal like this

```
beforeOpen: function() {
  modal.setContent(document.getElementById('detail').innerHTML);
},
```

Thank you.
