### ISSUE TITLE
Add convenient wrapper for confirm and alert

### ISSUE THREAD

**Issue by robinparisi** [robinparisi/tingle#16]
Example:

```
var confirm = new tingle.confirm({
  content: "Here's some content",
  onConfirm: function(){
    // on confirm process
  },
  onCancel: function(){
    // on cancel process
  }
});
```

Consider using the same approache for alerts.

**Comment by juanvillegas** [comment]
We implemented a wrapper around your library to display messages in our app (rocketlanguages.com). And needed "sugar" for confirm and alert. We solved this using Promises, which resulted pretty well. In case anyone is interested, here is a simplified example (our wrapper has some more use-case specific stuff):

- We created a window.RocketMessages namespace and added _confirm()_ and _alert()_ to it
- Calling _confirm()_ creates a tingle modal with some defaults and returns an ES6 promise, like so:

```javascript
return new Promise((resolve, reject) => {
    tingleModalObject.addFooterBtn("Ok button", "your class", () => { resolve(true); });
    tingleModalObject.addFooterBtn("Cancel button", "your class", () => { resolve(false); });
});
```

- In your client code, you can use it like:

```javascript
window.RocketMessages.confirm("Confirm delete?").then((userResponse) => {
    if (userResponse) {
       // user clicked "ok"
    } else {
       // user clicked "cancel"
    }
});
```

Good work by the way!
Cheers!
