### ISSUE TITLE
map inside modal

### ISSUE THREAD

**Issue by sstanisslav** [robinparisi/tingle#20]
Is there a way to display correctly map inside modal ?

**Comment by robinparisi** [comment]
Hi,

Can you be more specific ?

**Comment by sstanisslav** [comment]
If adding any script to render a map, it doesn't show up in modal until I resize the window.

**Comment by robinparisi** [comment]
It will be difficult to catch the bug without an example.

**Comment by mscreenie** [comment]
I had the same problem however tingle is not at fault, the script is asynchronously and you need to add a callback with the map api to resize the modal after the map has loaded.

**Comment by robinparisi** [comment]
This should no longer be a problem with flexbox support.
