### ISSUE TITLE
F is null

### ISSUE THREAD

**Issue by Ishimoi** [robinparisi/tingle#28]
Hey ... I created a basic HTML file
include the CSS file and the dist file "tingle.min.js"
and things happens...
i get a "f is null"  error on the console log

**Comment by Biptaste** [comment]
I have the same issue, it's happening when you load "tingle.js" in the <head>, to solve it put your js at the end of <body>

**Comment by Ishimoi** [comment]
Yeah.. It's worked!!Thanks 
 .. BUT i called the model in the $(document).ready() event..
Thanks!
