### ISSUE TITLE
Don't close modal when clicking outside

### ISSUE THREAD

**Issue by 0rsa** [robinparisi/tingle#33]
Hello,
Thanks to the author for his work.
I suggest this feature: add an option to disable closing modal when clicking outside the modal.
Although, there is a conflict between this closing event and scrollbar when content is too big: you cannot use left click mouse to move the scrollbar because it will automatically trigger closing event.
Thanks to read me.
See you

**Comment by robinparisi** [comment]
Hi,

Indeed, this is due to my last commit. I have to find a better way to handle click outside of the modal and I'm going to work on this quickly.
