### ISSUE TITLE
Retaining transitionEvent check with onClose

### ISSUE THREAD

**Issue by brianmontanaweb** [robinparisi/tingle#34]
Could I do a PR to update transitionEvent for onClose as an option?

If I want to destroy the modal after a user closes it, the action happens immediately, lemme know if that's something I can work on :smile:

**Comment by robinparisi** [comment]
Hi,

So you added a transition on close but it doesn't work since the close event is triggered immediately (and destroy the modal)? 

In this case, onClose callback should work the same as onOpen callback and use transitionend event.
