### ISSUE TITLE
Full-screen content not scrolling properly on iOS

### ISSUE THREAD

**Issue by kresic-ivan-nsoft** [robinparisi/tingle#36]
Hi there,

the full-screen (big) content has an issue with the scroller on iOS, both on Chrome and Safari: when the content is too big and needs to be displayed with a scrollbar, any scrolling attempts scroll the blurred background page, not the modal content. I'll try to fix it myself as well, will post update if I do.

**Comment by robinparisi** [comment]
Hi,

I don't have an IOS device to reproduce the bug. I'll try to find one to do some tests.

**Comment by ShoryLee** [comment]
I have the same issue like you.
On PC, Chrome or other browsers could not scroll when i first open the modal, but second time, it works!

**Comment by tempywritescode** [comment]
Same issue as @ShoryLee , on PC you have to open it twice before scrolling works.

**Comment by pacMakaveli** [comment]
@ShoryLee @tempywritescode best way to handle this, is to call `.checkOverflow()` in the `opOpen()` function.

**Comment by emmanuelballery** [comment]
Hi! (ou salut cher voisin de Troyes)

With asynchronous content (img ...) the scroll does not appear indeed (which seems logical, height cannot be guessed).

See : https://plnkr.co/edit/eHwMzb2ElPqqO4oQeCTs?p=preview (first time, no img in cache, no scroll)

Calling  `checkOverflow()` in the `onOpen` function is not ok, images may be not loaded yet when `onOpen` is called.

I ended up doing something like this :

```js
const imgs = modal.modal.getElementsByTagName('img');
for (let i in imgs) {
    if (imgs.hasOwnProperty(i)) {
        imgs[i].addEventListener('load', () => modal.checkOverflow());
    }
}
```

I don't think it's a Tingle issue but a bit of documentation somewhere could be a bonus.

Thanks!

**Comment by robinparisi** [comment]
Hey @emmanuelballery (jolie coïncidence 😄)

The scrolling issue was due to an another problem specific to iOS (https://benfrain.com/preventing-body-scroll-for-modals-in-ios/). A fix has been implemented and it should work fine now.

But you're totally right, in other case, it's necessary to attach an event listener to pictures which is meant to call the checkOverflow method.

**Comment by martinbroos** [comment]
I can confirm that the fix of @emmanuelballery works, it was still needed with async content that has images. I ended up using a library https://github.com/desandro/imagesloaded, this way it is a one liner:

`imagesLoaded(modal, modal.checkOverflow);`

this should be set in ajax response when the content has been set.
