### ISSUE TITLE
data-src not working inside modal

### ISSUE THREAD

**Issue by demonflair** [robinparisi/tingle#39]
I would like to add lazy loading to images inside the modal, and adding the data-src attribute wont work, the images simply don't show with this attribute.

**Comment by robinparisi** [comment]
Hi,

Can you post the affected part of your code?

**Comment by ginsterbusch** [comment]
My personal guess is that the script you're using is either firing too late or the event it's hooked to doesnt fire at all. But could be vice-versa: Firing too early, before the actual modal DOM data is ready. Lazyloading is a fine art.

Which of the many lazyloading scripts are you using? Or did you try to implement one by yourself? In the latter case, I'd suggest relying on existing solutions, eg. [lazyload-xt](https://github.com/ressio/lazy-load-xt) or [bLazy](https://github.com/dinbror/blazy/). That would help chasing down the issue - because if those, which are proven to work, do fail, then there is definitely something awry in the events department. One could also cross-check with the author(s) of the used script, for speeding up the search for the actual cause.

cu, w0lf.

**Comment by demonflair** [comment]
I did actually tried the bLazy, and it worked without the tingle. But with tingle the images fail to load completely. This is the way I set the images following with the script.

` 
<style>
 .b-lazy.animate{
		  opacity:0;
		  -ms-transform: scale(3);
		  -moz-transform: scale(3);
		  -webkit-transform: scale(3);
		  transform: scale(3);
		  -ms-transition: all 500ms;
		  -moz-transition: all 500ms;
		  -webkit-transition: all 500ms;
		  transition: all 500ms;
	  }

	  .b-loaded.animate {
		  opacity:1;
		  -ms-transform: scale(1);
		  -moz-transform: scale(1);
		  -webkit-transform: scale(1);
		  transform: scale(1);
	  }
</style>

<img class="b-lazy animate" src=data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw== data-src="http://cdn.dinbror.dk/assets/blazy/02.jpg" alt="Lazy load images example 1b" />

<script src="../blazy.js"></script>

	<script>
    window.bLazy = new Blazy({
		container: '.container',
		success: function(element){
			console.log("Element loaded: ", element.nodeName);
		}
	});
	</script>`

They do have a vertical container option, wondering if that is what is needed in this case. I will try this later.

**Comment by demonflair** [comment]
Ok, I have tested the container vertical option and it doesn't work. It appears that the modal doesn't recognize images with the data-src attribute. I've tried seeing if this would work at all outside the modal, to see if there were any other plugins generating a conflict with this attribute but it did worked perfectly outside the modal, although it definitely doesn't work with images set to data-src inside the modal.

It's a shame because this is by far the best modal plugin I've found to do what I want and I thank you for this Robin, but it would be perfect if lazy loading was possible.

**Comment by robinparisi** [comment]
I just tried on my side and it seems to work well :

[http://codepen.io/robinparisi/full/MJdgJO/](http://codepen.io/robinparisi/full/MJdgJO/)

**Comment by demonflair** [comment]
Thank you for helping me with this Robin, much appreciated. I've leaned that without this code the images wont load. Although I don't want to have the transition effect. Any chance the code can be removed in order for this to work?

`.tingle-modal-box {
  transition: transform .3s cubic-bezier(.175, .885, .32, 1.275);
  transform: scale(.8);
}`

**Comment by demonflair** [comment]
Ok, I managed to do this with a little cheat:

`.tingle-modal-box{position:relative;
    transition:transform .1s cubic-bezier(1,1,1,1);
    transform:scale(.9999999);
}`

This helped me reduce the page load significantly Robin, thank you so much for your awesome plugin, you Sir are a STAR!!!

In case you're curious to see how I applied it:

[www.vieira.com.pt](url)

**Comment by robinparisi** [comment]
@demonflair You're welcome, I'm glad to see that you like this plugin 😃 

For the CSS, you can just reset both properties :

```css
.tingle-modal-box { 
  transition: none;
  transform: none;
}
```
