### ISSUE TITLE
Having 2 Modals

### ISSUE THREAD

**Issue by BardiaKh** [robinparisi/tingle#41]
Hi

I want to get a confirmation when someone wants to close the modal. This confirmation is itself another modal! But when I summon the other modal it goes behind the original one!
is there any work around?

Thnx

**Comment by robinparisi** [comment]
Hi,

Tingle is not intended to allow multiple modals opened at the same time. You have basically two solutions :

1) close the first modal by using a callback and open the second one (you can always reopen the first one later)
2) replace content and buttons dynamically on the first modal to propose confirmation

**Comment by ginsterbusch** [comment]
It doesnt make sense anyway. A modal is consiered to be a a singular entity, not just another window.

BTW: I'd go with option #2 - replace content :)

cu, w0lf.

**Comment by BardiaKh** [comment]
Hello,
thanks for your response. I tried your 2nd option. So basically I use `modal.getContent()` and save it in a variable then use `modal.setContent("Bla Bla Bla...")` to create my confirmation message. 
The problem is when I want to set the modal content to the initial modal using my saved variable. Then I get this error:

> HierarchyRequestError (DOM Exception 3): The operation would yield an incorrect node tree.

**Comment by juanvillegas** [comment]
Probably a bit late but:
Have you tried adjusting your z-indexes? If you assign an extra class to your second modal ("more-important-modal-than-the-first-one") with a higher z-index, it should appear on top of the previous one.
I wouldn't bug my users like this anyway..

**Comment by robinparisi** [comment]
Hi @BardiaKh,

Sorry for the delay. If you're still struggling with this one, could you open a new issue and attach some code related to the setContent problem?
