### ISSUE TITLE
Close button invisible on iPhone

### ISSUE THREAD

**Issue by nickalie** [robinparisi/tingle#42]
![iphone](https://cloud.githubusercontent.com/assets/1968736/23297540/f69d284e-fa8a-11e6-88dd-d4d659e77d6a.png)

Tried with iOS 10.2

Though close button looks fine on iPad.

**Comment by nickalie** [comment]
```overflow: visible``` for ```.tingle-modal``` seems to solve the issue.

```
.tingle-modal {
  overflow: visible;
}
```

**Comment by NilsEvers** [comment]
Be careful when using `overflow: visible` as it might prevent you from scrolling. So if your modal content exceeds the size of your screen you won't be able to scroll.

**Comment by NilsEvers** [comment]
This is not only related to iOS Safari but to Safari in general.
To fix this, I moved the scrolling to the content box:

```
@media (max-width : 540px) {
  .tingle-modal {
    overflow: visible;
  }

  .tingle-modal--overflow {
    height: calc(100% - 60px);
  }
    
  .tingle-modal-box {
    height: 100%;
  }

  .tingle-modal-box__content {
    height: 100%;
    overflow-y: scroll;
  }
}
```
