### ISSUE TITLE
Flashing scrollbar in demo

### ISSUE THREAD

**Issue by tiffz** [robinparisi/tingle#43]
I haven't dived in yet enough to check if this happens in general, but the demo has the scrollbar flash away then back into view then back away when I try it out on Chrome, which I find a bit distracting. It would be nice for the scrollbar hiding to be made smoother.

**Comment by robinparisi** [comment]
Hi tiffz,

Indeed, I didn’t realize since scrollbars are always hidden on OSX. I will try to correct this when I have some time.
