### ISSUE TITLE
Blazy in modal thumbnails

### ISSUE THREAD

**Issue by demonflair** [robinparisi/tingle#47]
Hi Robin, I have a new issue regarding the blazy plugin in regards to your modal. This time I would like to use it in my portfolio thumbnails just as I used in the modals. But it works differently with code, and the way I'm coding isn't the correct way.
Here are the javascript codes I've tried:

`window.bLazy = new Blazy({
container: '.portfolio-wrapper',
success: function(element){
console.log("Element loaded: ", element.nodeName);
}
});`

`var thumbnails = new Blazy({
onLoad: function() {
new Blazy({
container: '.portfolio-wrapper'
})
}
});`

None worked... here is the thumbnail in html:

```
<div class="portfolio illustration" data-cat="illustration">
<div class="portfolio-wrapper">		
<button type="button" id="lightbox-1"><img class=""http://placehold.it/480x480/ffffff/ffffff" data-src="img/work/matrix typography/thumb.jpg" alt=""/></button>
<div class="label">
<div class="label-text">
<a class="text-title">Matrix Typography</a>
<span class="text-category">Illustration</span>
</div>
<div class="label-bg"></div>
</div>
</div>
</div>
```

I've created a separate class called "b-lazy-thumbs" and used it like this:

`||".b-lazy, .b-lazy-thumbs";a.options.separator=a.options.separator||`

**Comment by robinparisi** [comment]
Hi @demonflair,

Sorry for the delay. Like the previous time, I think your problem is more related to the use of Blazy so I can't really help on this (since I do not know Blazy very well).
