### ISSUE TITLE
Suggestion: Back button closes modal (at least on mobiles)

### ISSUE THREAD

**Issue by bridgeport** [robinparisi/tingle#48]
First off, thanks for this great script.

It would be nice if the modal closed upon clicking the back button on a mobile device.

This is something that's always bugged me about modals (probably more of a nag on Android devices). When I first took a look at your demo, then opened the modal, I reflexively clicked the back button to close it and ended up leaving your site. Yes, I see the close button. Yes, I've dealt with modals a million times, but on a mobile device automatic reflexes kick in and it's unavoidable. I doubt the regular website visitor handles this much different.

I've seen a few rare number of modal scripts tackle this, typically by having to juggle the browser's back and forward history. I found your script from vanillalist and none of the eight pure javascript modals they have listed implement this.

Some discussion on this topic:
http://www.mylearning.in/2015/06/close-modal-pop-up-on-back-button.html
http://ux.stackexchange.com/questions/53163/good-idea-to-have-back-button-close-a-modal-window
https://gist.github.com/thedamon/9276193
https://forum.ionicframework.com/t/closing-modal-with-android-back-button/3207/20

Thanks.

**Comment by ginsterbusch** [comment]
On a side note: I'd prolly solve that by using the browser history API. Has the advantage that its gonna work everywhere, not just on Androidic mobilistic browsers.

So eg. you click on the mobile, set history.path to "/modal/" or the modal internal name, and when next you press the back button, there is no automated redirect, but when the path "disappears",the modal disappears as well ;)

Essentially hooking into the history path event..

cu, w0lf.

**Comment by bridgeport** [comment]
@ginsterbusch Thanks for suggesting this. Yes, it does look like this could probably be put together by taking advantage of tingle's onOpen() and onClose() functions.

**Comment by robinparisi** [comment]
Hi @bridgeport,

I'm considering adding this feature in version 0.11

**Comment by robinparisi** [comment]
After a few thoughts (better late than never 😅), here is my feedback on the considered solutions:

- just override back button => I consider it as a dark pattern and really harmful for UX
- use window.location.hash => Can be a real problem with routers configured to use `#`
- use history.pushState => I don't think messing with history is a good idea

To be honest, I don't think modals are the best solution in a lot of UI / UX scenarios. However, I assume one thing: modals are just an alternative way to show information without losing context when we need to stay on the same page. So, modals shouldn't trigger a new push in history or we shouldn't use modals in such cases. I try to do my best to keep tingle non-specific while keeping UX in mind and in this case, I don't think back button or history will be beneficial.
