### ISSUE TITLE
The big modal on PC browser couldn't scroll when the first click

### ISSUE THREAD

**Issue by ShoryLee** [robinparisi/tingle#56]
On pc browsers, I must click button open and close the modal, then open it again the big modal can be scrolled.
Ps: I created the html content in js file, not in html file and set the display attribute.
Like this:   
`
var newDiv = "<p>Hello Word</p>...";   
modalBigContent.open();   
modalBigContent.setContent(newDiv );
`

**Comment by robinparisi** [comment]
Hi @ShoryLee,

Could you be more specific on this one (browser version, context, etc...) and share a bigger part of your code?

**Comment by ShoryLee** [comment]
Chrome 58.0.3029.110 (64-bit)   
When I open the modal first time, it can't scroll, then I close it. but I open it again(before refresh the page), it scroll well.   

`var modalBigContent = new tingle.modal();
//click to open
$('.content').on('click', function() {
    //get article id
    var contentId = $(this).children(':first').text();
    //ajax
    $.post('getDetails.php', {id: contentId}, function(data) {
        //parse json
        var jsonData = JSON.parse(data);
        // create content
        $.each(jsonData, function(index, item) {

            var details ='<div><h3 style="text-align:center">' + item.title + '</h3>' +
                         '<div class="content-font content-color content-line">' +
                         item.content + '</div>' +
                         '<p class="diary-time modal-by-text">' +
                         '<span class="diary-by-text content-font">归档于:&nbsp;' +
                         '<a class="under-line" href="http://localhost/jianguoCloud/TimeLineDiary/index.php?category=' + item.category + '">' +
                         item.category + '</a></span>&emsp;&emsp;' +
                         '<span class="content-font diary-by-text">撰写于:&nbsp;</span>' +
                         UnixToDate(item.created_at) +
                         '&emsp;<span class="content-font diary-by-text">最后修改于:&nbsp;</span>' +
                         UnixToDate(item.updated_at) + '</p></div>';
            //open modal
            modalBigContent.open();
            //fill the data
            modalBigContent.setContent(details); 
        });
    });
});`

**Comment by robinparisi** [comment]
Try to set content first then open the modal:

`
//fill the data
modalBigContent.setContent(details); 
//open modal
modalBigContent.open();
`

**Comment by ShoryLee** [comment]
Thanks very much.
