### ISSUE TITLE
Closing and then opening has unexpected results

### ISSUE THREAD

**Issue by gausie** [robinparisi/tingle#57]
Because the closing is slightly asynchronous, if you reopen the modal window too quickly, it can open and then instantly close as the previous asynchronous close event is fired.

**Comment by ginsterbusch** [comment]
So your indirect suggestion would be to have some kind of scheduler that avoids this race condition, yesyes? ;)

cu, w0lf.

**Comment by jordanmack** [comment]
I'm having an issue with this as well. In my case close() is being called almost immediately after open(). This is leaving some lingering close action which immediately closes the modal when it opens again, even if open() is called several seconds later.
