### ISSUE TITLE
Video does not stop on close

### ISSUE THREAD

**Issue by ncksnydr** [robinparisi/tingle#6]
If you play the YouTube video on the demo page and then close the modal, the video continues to play and the audio can be heard in the background.

As I integrate Tingle into my workflow components, I will attempt to fix the issue and submit a PR if you don't get to it first.

**Comment by robinparisi** [comment]
Hi,

Because Tingle only hide the modal on close, it's normal that the video keep playing. It's not related to Tingle and you have to handle the pause event by yourself inside the onClose() callback by using [Youtube API](https://developers.google.com/youtube/iframe_api_reference).

**Comment by ncksnydr** [comment]
Thanks for the reply. That definitely makes sense, but the example
definitely feels like a bug. I would suggest maybe adding a note about it
in the documentation. Feel free to close this issue.

On Mon, Apr 25, 2016 at 4:21 AM, Robin Parisi <notifications@github.com>
wrote:

> Hi,
>
> Because Tingle only hide the modal on close, it's normal that the video
> keep playing. It's not related to Tingle and you have to handle the pause
> event by yourself inside the onClose() callback by using Youtube API
> <https://developers.google.com/youtube/iframe_api_reference>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/robinparisi/tingle/issues/6#issuecomment-214271241>
>



-- 
Thanks,
___________________________

*Nick Snyder*
WEB:  http://nicksnyder.is
CELL: +1 856 630 3227

**Comment by robinparisi** [comment]
I agree that the example can be confusing. I will update it as soon as possible :smiley:
