### ISSUE TITLE
Add before open event/callback

### ISSUE THREAD

**Issue by azharp** [robinparisi/tingle#60]
Firstly, great plugin! Thank you for making this.

I was wondering if it is posibble to add before open event so that we can make some changes to the modal structure. For example I would like to change the close button with a custom one using an image or maybe you can add an option parameters to change the content of the close button.

Thank you

**Comment by craigpotter** [comment]
Extending this..... Can open a new issue/PR if needed.... should you be able to return false to stop the open as you can with the beforeClose ?
