### ISSUE TITLE
 Video does not stop when 'X' button is pressed (Playback sound continues to be heard)

### ISSUE THREAD

**Issue by congswow** [robinparisi/tingle#61]
When the 'X' button is pressed, the modal window is closed but the sound is playing, and the video being played seems to be alive in the background.
I hope that everything related to video is stopped at close time.

Thank you. A good day today

Ex.))

<div class="layout_area">
	<div class="movie">
		<a href="#" class="js-tingle-modal-1"><img alt="video" src="${pageContext.request.contextPath}/images/common/movie.png"></a>
			<div class="tingle-demo tingle-demo-tiny">
				<iframe width="854" height="480" src="https://youtu.be/XL9Ri8pO68w" frameborder="0" allowfullscreen></iframe>
	</div>
</div>

<script type="text/javascript">

    /**
    * Modal Tiny no footer
    */

    var modalTinyNoFooter = new tingle.modal({
        onClose: function() {
            console.log('close');
        },
        onOpen: function() {
            console.log('open');
        },
        beforeClose: function() {
            console.log('before close');
            return true;
        },
        cssClass: ['class1', 'class2']
    });
    var btn = document.querySelector('.js-tingle-modal-1');
    btn.addEventListener('click', function(){
        modalTinyNoFooter.open();
    });
    modalTinyNoFooter.setContent(document.querySelector('.tingle-demo-tiny').innerHTML);
    
  
    </script>

**Comment by RAMTO** [comment]
Had the same issue, so I am removing modal content onClose.
`modal.setContent('');`

**Comment by robinparisi** [comment]
Hi @congswow,

Since it's an iframe, you need to manage yourself the video (by removing content or using [YouTube player API](https://developers.google.com/youtube/iframe_api_reference?hl=fr)).
