### ISSUE TITLE
What browsers are supported?

### ISSUE THREAD

**Issue by MicahBrown** [robinparisi/tingle#65]
What browsers do you officially support? Looks like `classList` is used, so IE10+? What about Chrome, Safari, and FF?

**Comment by pacMakaveli** [comment]
https://caniuse.com/#search=classList has pretty good support.

**Comment by robinparisi** [comment]
Hi @MicahBrown,

I do not support IE < 11 but to be honest, I've never tested tingle on these older versions so it's possible that it works fine. No problem for the other browsers (Chrome, Safari and Firefox).
