### ISSUE TITLE
cant push framework.jar

### ISSUE THREAD

**Issue by churchthecat** [robinparisi/tingle#66]
7.1.2, LOS, magisk root, oneplus 3t

get this when i run main.py in admin command prompt.

D:\downloads\tingle-master\tingle-master>main.py
MENU

    1 - Patch file from a device (adb)
    2 - Patch file from the input folder

> 1

 *** OS: Windows 10 (win32)
 *** Python: 3.6.3 (64 bit)
 *** Mode: 1
 *** Working dir: C:\Users\Anders\AppData\Local\Temp\Tingle-l2o764_s
 *** Selected device: d0b87e19
 *** Automounting /system...
 *** Pulling framework from device...
      DEBUG: [  0%] /system/framework/framework.jar
[  1%] /system/framework/framework.jar
[  2%] /system/framework/framework.jar

[ 99%] /system/framework/framework.jar
[100%] /system/framework/framework.jar
/system/framework/framework.jar: 1 file pulled. 9.8 MB/s (6592846 bytes in 0.641s)
 *** Device SDK: 25
 *** Decompressing framework...
      DEBUG: Decompressing framework.jar
 *** Disassembling classes...
      DEBUG: Disassembling framework/classes.dex
 *** Patching...
 *** Detected: Android 8.x / 7.x / 6.x (or LOS/CM 13-14)
 *** Patching succeeded.
 *** Reassembling classes...
      DEBUG: Assembling out/classes.dex
 *** Recompressing framework...
      DEBUG: Compressing framework.jar
 *** Copying the patched file to the output folder...
 *** Rooting adbd...
 *** Unlocked ADB: True
 *** Remounting /system...
      DEBUG: Not running as root. Try "adb root" first.
 *** Pushing changes to the device...
      DEBUG: [  1%] /system/framework/framework.jar
[  2%] /system/framework/framework.jar
[  3%] /system/framework/framework.jar
[  4%] /system/framework/framework.jar
[  5%] /system/framework/framework.jar
[  6%] /system/framework/framework.jar
[  7%] /system/framework/framework.jar
[  8%] /system/framework/framework.jar
[  9%] /system/framework/framework.jar
[ 10%] /system/framework/framework.jar
[ 11%] /system/framework/framework.jar
[ 12%] /system/framework/framework.jar
[ 13%] /system/framework/framework.jar
[ 14%] /system/framework/framework.jar
[ 15%] /system/framework/framework.jar
[ 16%] /system/framework/framework.jar
[ 17%] /system/framework/framework.jar
adb: error: failed to copy 'framework.jar' to '/system/framework/framework.jar': remote couldn't create file: Read-only file system
framework.jar: 0 files pushed. 24.0 MB/s (1179648 bytes in 0.047s)
Traceback (most recent call last):
  File "D:\Downloads\tingle-master\tingle-master\main.py", line 573, in <module>
    output = subprocess.check_output([DEPS_PATH["adb"], "-s", SELECTED_DEVICE, "push", "framework.jar", "/system/framework/framework.jar"], stderr=subprocess.STDOUT)
  File "C:\Python36\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Python36\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\ProgramData\\chocolatey\\bin\\adb.exe', '-s', 'd0b87e19', 'push', 'framework.jar', '/system/framework/framework.jar']' returned non-zero exit status 1.

**Comment by robinparisi** [comment]
Hi @churchthecat,

Tingle is a JavaScript modal plugin so I think this is not the repo you're looking for.
