### ISSUE TITLE
Changing the top A- close icon to something else.

### ISSUE THREAD

**Issue by Oktai** [robinparisi/tingle#73]
Sorry lads,

I'm still a relative junior when it comes to web dev, so I'm still learning. But I'm struggling to change the A- close icon to a X. I've tried multiple things, such as placing the whole modal HTML with my own HTML file, and changing it manually, but it still doesn't.

There has to be an easier way, no?

**Comment by pacMakaveli** [comment]
@Oktai What exactly are you trying to change? The close button is already an X .

**Comment by Oktai** [comment]
![image](https://user-images.githubusercontent.com/9645533/35966564-0a4b99a0-0cb6-11e8-9984-3063d67b5f4e.png)

The modal close button has always been "A-" instead of a X. It's been that since I first tried to use Tingle a while ago. I don't really know how to change it, since I'm new to all of this.

**Comment by pacMakaveli** [comment]
That looks like bad encoding or something. It's not Tingle.
Post your HTML and let's see if we can find the 🐛 . I'm thinking your html doesn't have utf set or something!

**Comment by Oktai** [comment]
I'm in the midst of just revamping my html and site atm. After that's done, I'll see if the problem persists and then post it here.

**Comment by Oktai** [comment]
Do you want the whole HTML of the page? Or the html of the tingle modal?

**Comment by pacMakaveli** [comment]
@Oktai I'd probably need to HTML of the page itself. If you changed the HTML that Tingle uses, than I would need that as well.

**Comment by Oktai** [comment]
This has some elements missing due to them being SVGs.

https://codepen.io/anon/pen/qxRjvX

It's not opening the modal atm since my tingle.js files are all local. If you need to see it working, I can see if I link via a CDN. You'll have to excuse me, I'm a complete beginner at this, so I'm learning as I go.

**Comment by pacMakaveli** [comment]
https://codepen.io/anon/pen/qxRjvX

<img width="746" alt="screen shot 2018-02-09 at 9 48 59 am" src="https://user-images.githubusercontent.com/894272/36021686-76531542-0d7e-11e8-9877-dec92454d4c7.png">

I can see the X

**Comment by Oktai** [comment]
You know, I think you're right there.

I've been using bitballoon as a free way to be able ot show my friends where I'm at and so on, and I just checked on there. The X is showing, I think it's that my files aren't being compiled as you said.

Thank you for your help with all of this, regardless. I appreciate it!
