### ISSUE TITLE
Issue with body tag style

### ISSUE THREAD

**Issue by RyanGosden** [robinparisi/tingle#76]
I'm not sure if this is related to issue #74.

Upon opening the modal, a top style property is added to the body element. 
ie: `<body class="tingle-enabled" style="top: -689px;">`

Although when closing the modal, this value does not get removed which:
1. Leaves additional space at the bottom of the page.
2. Unable to scroll to the top. (content 'cropped');

**Comment by robinparisi** [comment]
Hi @RyanGosden,

I just published a new version (0.13.2) which should fix your issue.

**Comment by RyanGosden** [comment]
@robinparisi - Tested and issue is resolved. I must say, that was the quickest resolution I have seen to this date. Many thanks.
