### ISSUE TITLE
Question about instantiate multiple items

### ISSUE THREAD

**Issue by jayhlee** [robinparisi/tingle#77]
Is there another way to instantiate multiple modals instead of doing it within a script tag? I have a page with a roster of speakers, and I'm trying to set each bio to present a modal of the speaker's bio. From what I see, the only way to instantiate each speaker's bio modal is within a script tag.

**Comment by robinparisi** [comment]
Hi @jayhlee,

I'm not sure to understand the question, could you be more specific?
