### ISSUE TITLE
Trigger overflow content check on setContent()

### ISSUE THREAD

**Issue by MicahBrown** [robinparisi/tingle#79]
I'm appending ajax-ed content to the modal using `setContent()`. The issue is that the content is initially blank when the modal is opened and doesn't overflow the page. However, when the content is added, it overflows the page and the `.tingle-modal--overflow` class is never added since it only triggers on window resize (as I can see), but not `setContent()`. I therefore cannot scroll with the content now overflowing the page. 

My work around looks something like this:

```javascript
var modal = new tingle.modal();
modal.open(); // modal content doesn't yet overflow the page at this point since it's blank

$.get('/ajax_content_url', function(response){
  modal.setContent(response) // modal content now overflows page, but I can't scroll since there's no .tingle-modal--overflow in the modal classes
  modal._events.resize() // here's my workaround; manually calling resize to check if new content makes modal overflow page
})
```

But I think `setContent()` should trigger the `resize` event automatically.

**Comment by robinparisi** [comment]
Hi @MicahBrown,

There is a public method specially made for this case:

```js
var modal = new tingle.modal();
modal.open(); // modal content doesn't yet overflow the page at this point since it's blank

$.get('/ajax_content_url', function(response){
  modal.setContent(response);
  modal.checkOverflow();
})
```

**Comment by MicahBrown** [comment]
That may be so. I still think that checkOverflow should be called within
setContent since it's an entry point for new dynamic content. Don't you
think?

**Comment by robinparisi** [comment]
In this case, it would be great to check if the modal is open before calling the checkOverflow method in setContent.

**Comment by MicahBrown** [comment]
@robinparisi I updated my PR.

**Comment by robinparisi** [comment]
@MicahBrown Thanks, I've just merged your PR. It will be available in the next release.

**Comment by MicahBrown** [comment]
Sweet, thanks!
