### ISSUE TITLE
Footer with two buttons raises scrolling issues on iOS

### ISSUE THREAD

**Issue by VoordeMensen** [robinparisi/tingle#82]
When the footer has two buttons they are stacked on top of each other, partly covering the content of the modal:

![image](https://user-images.githubusercontent.com/35703448/38201023-f55775f4-3696-11e8-966e-cbce6f2f93ab.png)

This also seems to raise some scrolling issues on iOS, the modal sometimes stops scrolling and even the footer buttons stop responding. 

See https://dev.voordemensen.nl - click "Tickets" button.

**Comment by MamatmurodovA** [comment]
+

**Comment by CodeWithOz** [comment]
@VoordeMensen hey did you end up solving this issue? I want to use this lib so I'm wondering if I will still have to deal with this. Thanks!

**Comment by VoordeMensen** [comment]
Hi Oz, 

We've decided to only use Tingle on desktop and tablets, on iOS there we're too many issues with scrolling so we're redirecting users directly to our own servers. Solved all of our problems with iframes, cross domain cookies, etc.

Best, V

**Comment by CodeWithOz** [comment]
@VoordeMensen thanks for the feedback! Just curious, have you recently tried using tingle again on iOS? Asking because this issue was originally created in April 2018 so I'd like to know if you've tried again to get it working on iOS since then.

**Comment by VoordeMensen** [comment]
We're using a slightly older version than the latest master here yes, but that doesn't seem to cover these issues. Note that what we tried to do: load external iframe, two buttons, on iOS was pushing it maybe to the limits. Also iOS is very perky with modal scrolling, SO is full of overflow-issues and constantly changing so for an updated experience you could try for yourself. Goodluck!

**Comment by CodeWithOz** [comment]
@VoordeMensen thanks! I won't be using it in an iframe, do you only use it inside an iframe or do the same issues persist even in the main DOM? And yeah I'm aware of iOS' problems with modals, long-running issues.

**Comment by robinparisi** [comment]
I recently switch to iOS. 

I have no problem with tingle after some tests, padding bottom for content is dynamicaly calculated, so everything should be fine: https://github.com/robinparisi/tingle/blob/6e93c1bde6ec931fc8b641d7b8bec72b0979ee03/dist/tingle.js#L225

Anyway, I was unable to reproduce scrolling issues.
