### ISSUE TITLE
Uncaught ReferenceError: tingle is not defined

### ISSUE THREAD

**Issue by jarekkowol** [robinparisi/tingle#88]
Problem if site has require.js.

```
(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        define(factory);
    } else if (typeof exports === 'object') {
        module.exports = factory();
    } else {
        root.sendflow = factory();
    }
}(this, function() {
...
```

What is the purpose of defining factory without a library's name? How will I be able to get access to it when I need it?

**Comment by robinparisi** [comment]
Hi,

Could you share the part of your code where you're trying to load tingle ?

**Comment by jaypatel512** [comment]
I am running into this issue. I am creating a widget plugin that people can host on their site by just adding my javascript. It seems to fail on some websites, and yes, the ones that are not working uses require.js. 

Do you know how to were you able to fix that @jarekkowol ?
