### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by flyingangel** [robinparisi/tingle#90]
Hi, nice project!
I made a fork on the project and I'd like to contribute some changes.

Here is the project : https://github.com/flyingangel/tingle

Functionnalities added :
- adding a dark theme, it becomes the default one
- adding fullscreen mode; the content will not be centered on the page but begin from top left corner of the screen
- adding a new css class : success (green)
- change addFooterBtn to addBtn because there is no such thing as addHeaderBtn
- reworked addBtn function by using a JSON config instead of simple arguments; before it's difficult to add the 2nd parameter because you have to add the classname everytime
- adding 2 functions to mimic the native `window.alert()` and `window.confirm` (depends on Promise and not work for IE)

**Comment by robinparisi** [comment]
Hi @flyingangel,

There are a lot of great ideas here! Here are my thoughts about the features:

- a dark theme could be great (preferably in an alternative stylesheet) 
- a full-screen mode can be achieved with a custom class (I encourage this approach on tingle)
- the CSS will be refactored soon (I'm not happy with it)
- the change on addFooterBtn is planned for version 1.0 (breaking change)
- indeed, the addBtn api could be better
- tingle definitely needs alert and confirm but I would like to keep IE support

Let me merge the current PR and let's see what we can do about this 😃

**Comment by flyingangel** [comment]
- extern css theme, good idea
- currently all you need to activate fullscreen mode is to add that css class to the constructor
- if you need IE support, the easiest way is to do is to use callbacks instead of Promise.

Yes it's time to release version 1.0, the library is good enough to use in public :)
