### ISSUE TITLE
Enhancement: (sticky) header?

### ISSUE THREAD

**Issue by blubbll** [robinparisi/tingle#91]
Hi, i added a sticky header to a project i'm working on, would love to see this as an official feature.
Inspired by the ugly and undynamic bootstrap modals, i appended a header to tingle using some jQuery magic:

https://codepen.io/Blubbll/full/aKpoWo/

I'd be interested in hearing yours and maybe other people's opinion on this.
And maybe setting a custom height would be cool as well.

Thanks for creating this plugin anyway, it's way better and dynamic than using some combination of js, jQuery and DOM code for modals and helps me a lot.

**Comment by coxy17** [comment]
any update on this? would be great
