### ISSUE TITLE
Form submission in modal (from a Marketo JS embed)

### ISSUE THREAD

**Issue by clarklab** [robinparisi/tingle#97]
Hey!

Has anyone run into a situation where embeded content (in this case, some form JS from Marketo) would work outside the modal but not inside?

I'm assuming that grabbing the form with innerHTML is breaking the tie it had back to the controlling JS. Anyone seen something similar?

Here's the pertinent bits:

```
<div class="modal hide" id="follow">
	<div class="access modal center">
	<script src="https://marketo.com/js/forms2/js/forms2.min.js"></script>
	<form id="mktoForm_XXXX"></form>
	<script>MktoForms2.loadForm("https://marketo.com", "XXX-XXX-XXXX", XXXX);</script>
	</div>
</div>


 <script type="text/javascript">

 	var modal = new tingle.modal({
        footer: false,
        stickyFooter: false,
        closeMethods: ['overlay', 'button', 'escape'],
        closeLabel: "Close"
	});

	// set content
	modal.setContent(document.querySelector('#follow').innerHTML);
```

The modal opens fine, the form renders fine, but submit seems to be broken. No JS errors anywhere in the console (from Tingle, or from the Marketo form).

Halp?

**Comment by clarklab** [comment]
I should note that normally this works fine for me. I've done a handful of JS embeds, all inserted via innerHTML, where no JS functionality breaks. So kinda curious what's going on here...

**Comment by robinparisi** [comment]
Hi @clarklab,

Can't test Marketo right now but at first glance, I've got a 404 error on this URL https://marketo.com/js/forms2/js/forms2.min.js

**Comment by clarklab** [comment]
Hey @robinparisi! 

I changed the URL when posting because it had possibly custom info in it.

The JS fires, because a form shows up. It just won't submit. If I render the form outside a modal, it submits just fine.

**Comment by robinparisi** [comment]
And if you remove innerHTML?

```
// set content
modal.setContent(document.querySelector('#follow'));
```

**Comment by jaks19** [comment]
Hi OP and robinparisi.
Q to OP: did it finally work? is there a specific reason why you need the innerHTML specifically?

Q to robin: is this how you recommend putting a form for posting data in a modal? I cannot find online references on putting a form in the modal. If there are no issues with using forms, I will integrate tingle in my code for sure!

Thanks!
