### ISSUE TITLE
Open thingle the second time, all content is selected

### ISSUE THREAD

**Issue by laoneo** [robinparisi/tingle#98]
When opening the modal without a page refresh a second time on Firefox, then all content is selected. You can also reproduce the issue on your demo site. When clicking on "A simple modal" the second time, then it looks like:

![image](https://user-images.githubusercontent.com/251072/43949416-b6804344-9c8d-11e8-8cb5-5ccf32bd2d4e.png)

**Comment by eslsys** [comment]
This issue seems to be FF only

**Comment by OssiPesonen** [comment]
I fixed this on FF 62.0.3 (64-bit) by adding de-selection to the beforeOpen() callback after noticing this issue:
     
    beforeOpen: function() {
        document.getSelection().removeAllRanges();
    }

**Comment by laoneo** [comment]
Thanks that helped. Hope the maintainers get an idea then where to look for the root cause.

**Comment by laoneo** [comment]
Thanks!

**Comment by robinparisi** [comment]
You're welcome :smiley:. The best way to fix this is to use the ```user-select``` property so it's better to remove the getSelection() trick.
